apiVersion: v1
kind: Service
metadata:
  name: kwetter-kweet-service
  namespace: default
  labels:
    app: kwetter-kweet-service
    service: kwetter-kweet-service
spec:
  selector:
    app: kwetter-kweet-service-pod
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetter-kweet-service
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kwetter-kweet-service-pod
      version: latest
  template:
    metadata:
      labels:
        app: kwetter-kweet-service-pod
        version: latest
    spec:
      containers:
        - name: kwetter-kweet-container
          image: eu.gcr.io/s64-1-vetis/marco/kwetter/kwetter-kweet-service:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: kweet-service-mongo-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80