name: KweetService

on:
  push:
    branches: [ master ]
    paths:
      - src/Services/KweetService/**
  pull_request:
    branches: [ master ]
    paths:
      - src/Services/KweetService/**

defaults:
  run:
    working-directory: src
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build-docker:
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker KweetService image
        run: docker build . --file Services/KweetService/Rest/Dockerfile --tag kwetter-kweet-service:$(date +%s)
        
  publish-docker:
    if: contains(github.ref, 'master')
    needs: [build-docker]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: marcovstiphout/kwetter-kweet-service
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Services/KweetService/Rest/Dockerfile   
        workdir: src